{
    'name': "Yodoo ITSM",

    'summary': """
        Service Desk / Helpdesk / Requests / Tickets
    """,

    'author': "Center of Research and Development",
    'website': "https://crnd.pro",
    'version': '17.0.0.7.0',
    'category': 'Service Desk',

    # any module necessary for this one to work correctly
    'depends': [
        'base_field_m2m_view',
        'crnd_vsd',
        'crnd_vsd_field_set',
        'crnd_vsd_location',
        'crnd_vsd_resource',
        'crnd_vsd_tag',
        'crnd_web_diagram_plus',
        'crnd_web_on_create_action',
        'crnd_web_tree_colored_field',
        'generic_assignment',
        'generic_assignment_team',
        # 'generic_business_process',
        'generic_condition',
        'generic_condition_automation',
        # 'generic_equipment',
        'generic_location',
        'generic_m2o',
        'generic_mixin',
        'generic_request',
        'generic_request_action',
        'generic_request_action_assignment',
        'generic_request_action_hr',
        'generic_request_action_project',
        'generic_request_action_survey',
        'generic_request_action_team',
        'generic_request_action_todo',
        'generic_request_address',
        'generic_request_assignment',
        'generic_request_assignment_team',
        'generic_request_calendar',
        'generic_request_condition',
        'generic_request_condition_mail',
        'generic_request_crm',
        'generic_request_deadline',
        'generic_request_field',
        'generic_request_field_set',
        'generic_request_hr',
        'generic_request_invoicing',
        'generic_request_location',
        'generic_request_mail',
        'generic_request_mail_action',
        'generic_request_message_status',
        'generic_request_project',
        # 'generic_request_rating',
        'generic_request_recent',
        'generic_request_related_doc',
        'generic_request_related_requests',
        'generic_request_resource',
        'generic_request_route_auto',
        'generic_request_sale',
        'generic_request_sla',
        'generic_request_sla_log',
        'generic_request_sla_team',
        'generic_request_survey',
        'generic_request_team',
        'generic_request_todo',
        'generic_request_weight',
        'generic_resource',
        'generic_resource_location',
        'generic_resource_role',
        # 'generic_resource_role_hr',
        'generic_resource_timesheet',
        'generic_resource_type_builder',
        'generic_rule',
        'generic_service',
        'generic_service_team',
        'generic_system_event',
        # 'generic_system_event_automation',
        # 'generic_system_event_crm',
        # 'generic_system_event_hr',
        'generic_system_event_mail_events',
        'generic_system_event_project',
        'generic_tag',
        # 'generic_tag_automation',
        'generic_team',
        'generic_team_tag',
        'generic_todo',
        'generic_todo_automatization',
        'generic_todo_project',
    ],

    # always loaded
    'data': [
    ],
    'images': ['static/description/banner.png'],
    'demo': [],

    'installable': True,
    'application': True,
    'license': 'OPL-1',
    'tags': ['bundle'],

    'price': 1.0,
    'currency': 'EUR',
    "live_test_url": "https://yodoo.info",
}
