from . import (
    test_request,
    test_request_simple_flow,
    test_access_rights,
    test_request_author,
    test_mail,
    test_request_timesheet,
    test_request_wizard_close,
    test_rpc_channel,
    test_request_events,
    test_request_service,
    test_wizard_set_parent,
    test_request_tags,
    test_request_classifier,
)
